Artifacts:
- SourceArtifact: coredns/coredns
  Tags:
  - 1.14.6
  - 1.14.7
- SourceArtifact: library/busybox
  Tags:
  - 1.37.0
- SourceArtifact: library/traefik
  Tags:
  - 3.7.12
  - 3.7.13
- SourceArtifact: registry.k8s.io/metrics-server/metrics-server
  Tags:
  - v0.9.0
  TargetArtifactName: mirrored-metrics-server
- SourceArtifact: registry.k8s.io/pause
  Tags:
  - "3.10"
  - 3.10.2
  TargetArtifactName: mirrored-pause
- SourceArtifact: docker.io/rancher/local-path-provisioner
  Tags:
  - v0.0.37
  TargetArtifactName: mirrored-local-path-provisioner
Repositories:
- BaseUrl: ghcr.io/vitorsavian
  DefaultTarget: true
  Registry: ghcr.io
  RepoAuth: true
