name: Pull request checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: |
          cd tools
          go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Run linter
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          working-directory: tools
          args: --timeout=5m

  formatting-is-valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Ensure that files are formatted correctly
        run: |
          scripts/build-tools.sh
          bin/image-mirror-tools format
          # fail if there are changes in the working tree
          git diff --exit-code

  regsync-yaml-synced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Ensure that regsync.yaml is in sync with config.yaml
        run: |
          scripts/build-tools.sh
          bin/image-mirror-tools generate-regsync
          # fail if there are changes in the working tree
          git diff --exit-code

  run-validate-subcommand:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.24'

      - name: Run bin/image-mirror-tools validate
        run: |
          scripts/build-tools.sh
          bin/image-mirror-tools validate --merge-base-branch origin/master
